esphome:
  name: pm-sensor
  name_add_mac_suffix: true

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API, disable if using MQTT
#api:
#  password: "freshair"

ota:
  - platform: esphome
    password: "freshair"

#Enables Wifi connection
wifi:
  ssid: "MariaD05"
  password: "ragus123"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pm-Sensor Fallback Hotspot"
    password: "freshair"

#Enables a web dashboard accessible via ESP32 IP if connected to same local network
web_server:
  port: 80

captive_portal:

#Enables MQTT
mqtt:
  broker: mqtt ip
  username: pm-sensor
  password: freshair
  client_id: pm-sensor

#Enables I2C connection 
i2c:
  sda: 6
  scl: 7
  scan: true
  id: bus_a

sensor:
  - platform: pmsa003i
 # This fixed a problem where the board would't report anything when it's plugged in
    setup_priority: -100
    #Sets readings to standard units if true, environmental units if false
    standard_units: True
    # Overall sample frequency. 
    # NOTE: update_interval * window_size = time to get accurate calculated average
    update_interval: 5s
    # PM sensor values  
    pm_2_5:
      name: "PM2.5"
      id: "pm025"
      #For MQTT
      state_topic: pm-sensor/pm2.5
      filters:
      - sliding_window_moving_average:
        # Take this number of readings and calculate the average 
          window_size: 5
        # Push out the average after this number of readings  
          send_every: 5
      on_value:
        # Calculates PM2.5 AQI based on USA EPA formula when each 'send_every' reading is published 
        # https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
        lambda: |-
          } else if (id(pm025).state < 35.4) {
            // moderate
            id(pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 12.1) * (id(pm025).state - 12.1) + 51.0);
          } else if (id(pm025).state < 55.4) {
            // usg
            id(pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(pm025).state - 35.5) + 101.0);
          } else if (id(pm025).state < 150.4) {
            // unhealthy
            id(pm_2_5_aqi).publish_state((200.0 - 151.0) / (150.4 - 55.5) * (id(pm025).state - 55.5) + 151.0);
          } else if (id(pm025).state < 250.4) {
            // very unhealthy
            id(pm_2_5_aqi).publish_state((300.0 - 201.0) / (250.4 - 150.5) * (id(pm025).state - 150.5) + 201.0);
          } else if (id(pm025).state < 350.4) {
            // hazardous
            id(pm_2_5_aqi).publish_state((400.0 - 301.0) / (350.4 - 250.5) * (id(pm025).state - 250.5) + 301.0);
          } else if (id(pm025).state < 500.4) {
            // hazardous 2
            id(pm_2_5_aqi).publish_state((500.0 - 401.0) / (500.4 - 350.5) * (id(pm025).state - 350.5) + 401.0);
          }
    pm_10_0:
      name: "PM10.0"
      id: "pm100"
      #For MQTT
      state_topic: pm-sensor/pm10
      filters:
      - sliding_window_moving_average:
        # // Take this number of readings and calculate the average 
          window_size: 5
        # //Push out the average after this number of readings  
          send_every: 5
      on_value:
        # Calculates PM10.0 AQI based on USA EPA formula when each 'send_every' reading is published
        # https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
        lambda: |-
          } else if (id(pm100).state < 55) {
            // moderate
            id(pm_10_0_aqi).publish_state((100.0 - 51.0) / (154 - 55) * (id(pm100).state - 55) + 51.0);
          } else if (id(pm100).state < 155) {
            // usg
            id(pm_10_0_aqi).publish_state((150.0 - 101.0) / (254 - 155) * (id(pm100).state - 155) + 101.0);
          } else if (id(pm100).state < 354) {
            // unhealthy
            id(pm_10_0_aqi).publish_state((200.0 - 151.0) / (354 - 255) * (id(pm100).state - 255) + 151.0);
          } else if (id(pm100).state < 424) {
            // very unhealthy
            id(pm_10_0_aqi).publish_state((300.0 - 201.0) / (424 - 355) * (id(pm100).state - 355) + 201.0);
          } else if (id(pm100).state < 504) {
            // hazardous
            id(pm_10_0_aqi).publish_state((400.0 - 301.0) / (504 - 425) * (id(pm100).state - 425) + 301.0);
          } else if (id(pm100).state < 604) {
            // hazardous 2
            id(pm_10_0_aqi).publish_state((500.0 - 401.0) / (604 - 505) * (id(pm100).state - 505) + 401.0);
          } 
    # Particulate Matter Count sensor values  
    pmc_2_5:
      name: "PMC >2.5µm"
      id: "pmc025"
      #For MQTT
      state_topic: pm-sensor/pmc2.5
    pmc_10_0:
      name: "PMC >10µm"
      id: "pmc100"
      #For MQTT
      state_topic: pm-sensor/pmc10

    # Template sensor values for AQI Calculation   
  - platform: template
    name: "PM <2.5 AQI"
    unit_of_measurement: "AQI"
    accuracy_decimals: 0
    id: pm_2_5_aqi
    #For MQTT
    state_topic: pm-sensor/pm2.5aqi
  - platform: template
    name: "PM <10.0 AQI"
    unit_of_measurement: "AQI"
    accuracy_decimals: 0
    id: pm_10_0_aqi
    #For MQTT
    state_topic: pm-sensor/pm10aqi